# Generated by Django 6.0.1 on 2026-02-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('spec', models.CharField(max_length=60)),
                ('fee', models.IntegerField()),
                ('accr', models.BooleanField()),
            ],
        ),
    ]
